package lml.snir.drivers.lecteurrfid;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.Observer;

/**
 *
 * @author fanou
 */
public class IHM extends javax.swing.JFrame {
    private final Observer obs;
    private String content;

    /**
     * Creates new form IHM
     * @param obs
     */
    public IHM(Observer obs) {
        initComponents();
        this.jComboBoxBadge.removeAllItems();
        this.obs = obs;
        try {
            InputStream flux = new FileInputStream("./badges");
            InputStreamReader lecture = new InputStreamReader(flux);
            try (BufferedReader buff = new BufferedReader(lecture)) {
                String ligne;
                while ((ligne = buff.readLine()) != null) {
                    //System.out.println(ligne);
                    this.jComboBoxBadge.addItem(ligne);
                }
            }
        } catch (IOException e) {
            System.out.println(e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPassBadge = new javax.swing.JButton();
        jComboBoxBadge = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonPassBadge.setText("Passer");
        jButtonPassBadge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPassBadgeActionPerformed(evt);
            }
        });

        jComboBoxBadge.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBoxBadge, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButtonPassBadge)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxBadge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPassBadge))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPassBadgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPassBadgeActionPerformed
        this.content = (String) this.jComboBoxBadge.getSelectedItem();
        new Thread(new Runnable() {

            @Override
            public void run() {
                obs.update(null, content);
            }
        }).start();
    }//GEN-LAST:event_jButtonPassBadgeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPassBadge;
    private javax.swing.JComboBox<String> jComboBoxBadge;
    // End of variables declaration//GEN-END:variables
}
